name: DECODEJS
description: Trình giải mã JavaScript
version: 1.3.0
author: Nam Trường
author_email: hi@duongnamtruong.com
url: https://laptrinhbanthan.com/de4js
theme: jekyll-theme-hacker
show_downloads: false
google_analytics: UA-123121912-5
sass:
  style: compressed

exclude: ['Gemfile', 'Gemfile.lock', 'node_modules', 'package.json', 'package-lock.json']
